version: '3.9'
volumes:
  mysql-data:
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: users
    volumes:
       - mysql-data:/var/lib/mysql
    ports:
      - 33063:3306

  mockGf2:
    image: mockserver/mockserver
    ports:
      - 1080:1080
